trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/container-build/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Create archive from image
      imageName: $(tag)
      workingDirectory: /output
      volumes: |
        $(Build.ArtifactStagingDirectory):/target
      containerCommand: tar -czvf /target/$(tag).tgz lfs
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'hirstlinux-toolchain'
        publishLocation: 'Container'